//! verdict.rs — per-test rows and the reducer into the pipeline contract.
//!
//! Each `#[test]` writes its own `<id>.jsonl` row (like the bash harness appended
//! a JSONL row per assertion). `emit-verdict` then reduces every row into the
//! `verdict.json` the pipeline already consumes:
//!
//! ```json
//! {
//!   "platform": "linux", "box_commit": "abc123…", "verdict": "GREEN",
//!   "counts": { "total": 13, "pass": 12, "fail": 0, "error": 0, "skip": 1 },
//!   "by_category": { "policy": { "pass": 7, "fail": 0, "error": 0, "skip": 0 }, … },
//!   "integrity": { "cargo_status": 0, "expected": 13, "recorded": 13, "problems": [] },
//!   "coverage_gate": "full" | "reduced: 2 quarantined cell(s) on this platform",
//!   "quarantine": [ { "id", "platform", "reason", "issue", "owner", "restore_when", "applied" }, … ],
//!   "results": [ { "id", "category", "description", "result", "note" }, … ]
//! }
//! ```
//!
//! The reducer is fail-closed. GREEN needs every case in the compiled manifest
//! recorded exactly once with a known result, no FAIL, no ERROR, at least one PASS,
//! every SKIP either declared by the case's own `platforms:` list or an exact,
//! compiled TEMPORARY QUARANTINE cell carrying exactly its authorized note
//! (`quarantine.rs`, test-integ/QUARANTINE.md), no malformed row, and
//! `cargo test` itself exited 0. Anything else is RED, and `integrity.problems`
//! says why. A nonempty subset of rows, a crashed test binary, or a build that
//! never produced a test cannot read as a pass. While the quarantine list is
//! non-empty for the platform, `coverage_gate` reads `reduced` and the `quarantine`
//! array names every exempted cell: that GREEN is the reduced merge gate, not full
//! qualification.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

/// One case the suite compiles: its id, the folder it lives in, and the platforms
/// it declares (`platforms:` in `det_case!`); empty means every platform.
/// Generated by `build.rs` from the case files themselves.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CaseSpec {
    pub id: &'static str,
    pub category: &'static str,
    pub platforms: &'static [&'static str],
}

impl CaseSpec {
    /// Whether the case is declared to run on `platform`.
    pub fn applies_to(&self, platform: &str) -> bool {
        self.platforms.is_empty() || self.platforms.contains(&platform)
    }
}

/// Every case in the compiled suite, from the generated manifest.
pub const MANIFEST: &[CaseSpec] = include!(concat!(env!("OUT_DIR"), "/case_manifest.rs"));

/// The result vocabulary a row may carry. Anything else is malformed.
pub const RESULTS: &[&str] = &["PASS", "FAIL", "ERROR", "SKIP"];

/// The note prefix every declared-inapplicable SKIP row carries, written only by
/// `run_case_on`. A SKIP whose note does not start with this is a problem.
pub const SKIP_NOTE_PREFIX: &str = "not applicable on ";

/// The env var `run.sh` sets to `cargo test`'s exit status for `emit-verdict`.
pub const CARGO_STATUS_ENV: &str = "DET_CARGO_STATUS";

/// Where rows and verdict.json live. `$DET_RESULTS_DIR` else `~/det-results`.
pub fn results_dir() -> PathBuf {
    if let Ok(d) = std::env::var("DET_RESULTS_DIR") {
        if !d.is_empty() {
            return PathBuf::from(d);
        }
    }
    crate::user_home().join("det-results")
}

/// One recorded result — serialized as a single-line `<id>.jsonl` file. Field set
/// matches the bash JSONL rows.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Row {
    pub id: String,
    pub category: String,
    pub description: String,
    pub result: String,
    pub note: String,
}

/// The file a row for `id` is written to (one file per unique id, so parallel
/// tests never contend). The id is sanitized for use as a filename.
pub fn row_file(dir: &Path, id: &str) -> PathBuf {
    dir.join(format!("{}.jsonl", id.replace(['/', '\\'], "_")))
}

/// Write one row for a case. `note` is truncated to 9000 chars.
pub fn write_row(
    dir: &Path,
    id: &str,
    category: &str,
    description: &str,
    result: &str,
    note: &str,
) {
    let row = Row {
        id: id.to_string(),
        category: category.to_string(),
        description: description.to_string(),
        result: result.to_string(),
        note: note.chars().take(9000).collect(),
    };
    if let Ok(line) = serde_json::to_string(&row) {
        let _ = std::fs::write(row_file(dir, id), line + "\n");
    }
}

#[derive(Serialize, Default, Clone, Copy, Debug, PartialEq, Eq)]
pub struct Counts {
    pub total: usize,
    pub pass: usize,
    pub fail: usize,
    pub error: usize,
    pub skip: usize,
}

#[derive(Serialize, Default, Clone, Copy, Debug, PartialEq, Eq)]
pub struct CategoryCounts {
    pub pass: usize,
    pub fail: usize,
    pub error: usize,
    pub skip: usize,
}

/// How the suite executed, independent of what the rows say.
#[derive(Serialize, Clone, Debug, PartialEq, Eq)]
pub struct Integrity {
    /// `cargo test`'s exit status as `run.sh` reported it; `None` when not reported.
    pub cargo_status: Option<i32>,
    /// Cases in the compiled manifest.
    pub expected: usize,
    /// Well-formed rows read.
    pub recorded: usize,
    /// Every reason the verdict is not GREEN that the counts alone would hide.
    pub problems: Vec<String>,
}

#[derive(Serialize, Debug)]
pub struct Summary {
    pub platform: String,
    pub box_commit: String,
    pub verdict: String,
    pub counts: Counts,
    pub by_category: BTreeMap<String, CategoryCounts>,
    pub integrity: Integrity,
    /// `full` when no TEMPORARY QUARANTINE entry applies to this platform; otherwise `reduced: N
    /// quarantined cell(s) on this platform`. A GREEN with `reduced` is the explicitly reduced merge
    /// gate, never full qualification.
    pub coverage_gate: String,
    /// Every TEMPORARY QUARANTINE entry that applies to this platform, with whether its authorized
    /// SKIP row was actually recorded (additive; the collector ignores unknown keys).
    pub quarantine: Vec<crate::quarantine::QuarantineReport>,
    pub results: Vec<Row>,
}

/// What `read_rows` found: the rows that parsed, and a description of every file
/// or line that did not.
#[derive(Default, Debug)]
pub struct Rows {
    pub rows: Vec<Row>,
    pub malformed: Vec<String>,
}

impl Summary {
    /// Reduce `rows` for `platform` against `manifest`. `cargo_status` is the exit
    /// status of `cargo test`, `None` when the caller did not report one.
    pub fn build(
        platform: &str,
        box_commit: &str,
        rows: Rows,
        manifest: &[CaseSpec],
        cargo_status: Option<i32>,
    ) -> Self {
        let Rows {
            mut rows,
            malformed,
        } = rows;
        // Stable order: by id, so verdict.json is deterministic across runs.
        rows.sort_by(|a, b| a.id.cmp(&b.id));

        let mut counts = Counts::default();
        let mut by_category: BTreeMap<String, CategoryCounts> = BTreeMap::new();
        let mut problems: Vec<String> = malformed
            .iter()
            .map(|m| format!("malformed row: {m}"))
            .collect();

        for r in &rows {
            counts.total += 1;
            let cat = by_category.entry(r.category.clone()).or_default();
            match r.result.as_str() {
                "PASS" => {
                    counts.pass += 1;
                    cat.pass += 1;
                }
                "FAIL" => {
                    counts.fail += 1;
                    cat.fail += 1;
                }
                "ERROR" => {
                    counts.error += 1;
                    cat.error += 1;
                }
                "SKIP" => {
                    counts.skip += 1;
                    cat.skip += 1;
                }
                other => problems.push(format!("{}: unknown result {other:?}", r.id)),
            }
        }

        // Every manifest case exactly once; every row a manifest case.
        let mut seen: BTreeMap<&str, usize> = BTreeMap::new();
        for r in &rows {
            *seen.entry(r.id.as_str()).or_default() += 1;
        }
        let known: BTreeSet<&str> = manifest.iter().map(|c| c.id).collect();
        for spec in manifest {
            match seen.get(spec.id).copied().unwrap_or(0) {
                0 => problems.push(format!(
                    "{}: no row recorded (the test never ran, or its binary crashed before recording)",
                    spec.id
                )),
                1 => {}
                n => problems.push(format!("{}: {n} rows recorded (duplicate id)", spec.id)),
            }
        }
        for id in seen.keys() {
            if !known.contains(id) {
                problems.push(format!("{id}: row for a case not in the compiled suite"));
            }
        }

        // A SKIP only where the case declares the platform out, and never where it
        // declares the platform in; category as the folder says.
        for r in &rows {
            let Some(spec) = manifest.iter().find(|c| c.id == r.id) else {
                continue;
            };
            if r.category != spec.category {
                problems.push(format!(
                    "{}: category {:?} but the case lives in {:?}",
                    r.id, r.category, spec.category
                ));
            }
            let applies = spec.applies_to(platform);
            let quarantined = crate::quarantine::lookup(&r.id, platform);
            if r.result == "SKIP" {
                if applies {
                    match quarantined {
                        // The one authorized exception: the compiled cell AND exactly its note.
                        Some(q) if r.note == crate::quarantine::note(q) => {}
                        Some(_) => problems.push(format!(
                            "{}: SKIP on {platform} with a note that is not the authorized TEMPORARY QUARANTINE note \
                             (required coverage not exercised without authorization)",
                            r.id
                        )),
                        None => problems.push(format!(
                            "{}: SKIP on {platform}, but the case is declared for this platform (required coverage not exercised)",
                            r.id
                        )),
                    }
                } else if !r.note.starts_with(SKIP_NOTE_PREFIX) {
                    problems.push(format!(
                        "{}: SKIP without the declared-inapplicable note",
                        r.id
                    ));
                }
            } else if applies && quarantined.is_some() {
                // Runner and reducer read the same list; a recorded PASS/FAIL/ERROR here means they
                // disagreed (a stale build, a bypassed runner). Fail closed.
                problems.push(format!(
                    "{}: recorded {} on {platform}, but the cell is TEMPORARY-QUARANTINED (runner and reducer disagree)",
                    r.id, r.result
                ));
            } else if !applies {
                problems.push(format!(
                    "{}: recorded {} on {platform}, but the case is declared for {:?} only",
                    r.id, r.result, spec.platforms
                ));
            }
        }

        match cargo_status {
            None => problems.push(format!(
                "cargo test exit status not reported ({CARGO_STATUS_ENV} unset): the suite may not have run"
            )),
            Some(0) => {}
            Some(code) if counts.fail == 0 && counts.error == 0 => problems.push(format!(
                "cargo test exited {code} but no recorded row failed: a test outside the harness failed, or a binary crashed"
            )),
            Some(code) => problems.push(format!("cargo test exited {code}")),
        }

        if counts.pass == 0 {
            problems.push("no case passed: nothing was exercised".to_string());
        }

        // GREEN only if every case ran to a known outcome and nothing failed or
        // errored. An ERROR is an infrastructure fault (box never launched, CLI/load
        // refusal) — a case that proved nothing — so it turns the suite RED (the
        // fail-closed behavior added upstream), and so does every integrity problem above.
        let verdict = if counts.fail == 0 && counts.error == 0 && problems.is_empty() {
            "GREEN"
        } else {
            "RED"
        };

        // The exact coverage gap this platform's GREEN would carry, named for reviewers.
        let quarantine: Vec<crate::quarantine::QuarantineReport> =
            crate::quarantine::for_platform(platform)
                .into_iter()
                .map(|q| crate::quarantine::QuarantineReport {
                    id: q.id,
                    platform: q.platform,
                    reason: q.reason,
                    issue: q.issue,
                    owner: q.owner,
                    restore_when: q.restore_when,
                    applied: rows.iter().any(|r| {
                        r.id == q.id && r.result == "SKIP" && r.note == crate::quarantine::note(q)
                    }),
                })
                .collect();
        let coverage_gate = if quarantine.is_empty() {
            "full".to_string()
        } else {
            format!(
                "reduced: {} quarantined cell(s) on this platform",
                quarantine.len()
            )
        };

        Summary {
            platform: platform.to_string(),
            box_commit: box_commit.to_string(),
            verdict: verdict.to_string(),
            counts,
            by_category,
            integrity: Integrity {
                cargo_status,
                expected: manifest.len(),
                recorded: rows.len(),
                problems,
            },
            coverage_gate,
            quarantine,
            results: rows,
        }
    }
}

/// Read every `<id>.jsonl` row from `dir` (ignoring verdict.json). A file that is
/// not exactly one well-formed row, or whose row id does not match its filename, is
/// reported as malformed rather than dropped.
pub fn read_rows(dir: &Path) -> Rows {
    let mut found = Rows::default();
    let Ok(entries) = std::fs::read_dir(dir) else {
        found
            .malformed
            .push(format!("{}: results directory unreadable", dir.display()));
        return found;
    };
    let mut paths: Vec<PathBuf> = entries.flatten().map(|e| e.path()).collect();
    paths.sort();
    for path in paths {
        if path.extension().and_then(|e| e.to_str()) != Some("jsonl") {
            continue;
        }
        let name = path
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("?")
            .to_string();
        let content = match std::fs::read_to_string(&path) {
            Ok(c) => c,
            Err(e) => {
                found.malformed.push(format!("{name}: unreadable ({e})"));
                continue;
            }
        };
        let lines: Vec<&str> = content
            .lines()
            .map(str::trim)
            .filter(|l| !l.is_empty())
            .collect();
        if lines.len() != 1 {
            found.malformed.push(format!(
                "{name}: {} rows in one file (expected 1)",
                lines.len()
            ));
            continue;
        }
        match serde_json::from_str::<Row>(lines[0]) {
            Ok(row) => {
                if row_file(dir, &row.id) != path {
                    found
                        .malformed
                        .push(format!("{name}: holds a row for id {:?}", row.id));
                } else {
                    // A row with an unknown result is kept too: `Summary::build` reports it by id.
                    found.rows.push(row);
                }
            }
            Err(e) => found.malformed.push(format!("{name}: not a row ({e})")),
        }
    }
    found
}

/// `cargo test`'s exit status as `run.sh` reports it through the environment.
pub fn cargo_status_from_env() -> Option<i32> {
    std::env::var(CARGO_STATUS_ENV).ok()?.trim().parse().ok()
}

/// Reduce the rows in `dir` into `dir/verdict.json`. Returns the built summary.
pub fn emit(dir: &Path) -> std::io::Result<Summary> {
    let summary = Summary::build(
        crate::Platform::current().as_str(),
        &crate::resolve_box_commit(),
        read_rows(dir),
        MANIFEST,
        cargo_status_from_env(),
    );
    let json = serde_json::to_string_pretty(&summary).unwrap_or_default();
    std::fs::write(dir.join("verdict.json"), json + "\n")?;
    Ok(summary)
}

#[cfg(test)]
mod tests {
    //! Fault injection for the reducer: every way a partial or broken run could
    //! read as GREEN must come out RED with a named problem.
    use super::*;

    const SUITE: &[CaseSpec] = &[
        CaseSpec {
            id: "PO-1",
            category: "policy",
            platforms: &[],
        },
        CaseSpec {
            id: "CN-1",
            category: "containment",
            platforms: &[],
        },
        CaseSpec {
            id: "CN-MAC",
            category: "containment",
            platforms: &["macos"],
        },
    ];

    fn row(id: &str, category: &str, result: &str, note: &str) -> Row {
        Row {
            id: id.into(),
            category: category.into(),
            description: "d".into(),
            result: result.into(),
            note: note.into(),
        }
    }

    fn complete_linux() -> Vec<Row> {
        vec![
            row("PO-1", "policy", "PASS", ""),
            row("CN-1", "containment", "PASS", ""),
            row(
                "CN-MAC",
                "containment",
                "SKIP",
                &format!("{SKIP_NOTE_PREFIX}linux: declared for [macos]"),
            ),
        ]
    }

    fn build(rows: Vec<Row>, malformed: Vec<String>, status: Option<i32>) -> Summary {
        Summary::build("linux", "abc", Rows { rows, malformed }, SUITE, status)
    }

    #[test]
    fn complete_run_with_declared_skip_is_green() {
        let s = build(complete_linux(), vec![], Some(0));
        assert_eq!(s.verdict, "GREEN", "{:?}", s.integrity.problems);
        assert_eq!(
            s.counts,
            Counts {
                total: 3,
                pass: 2,
                fail: 0,
                error: 0,
                skip: 1
            }
        );
        assert_eq!(s.integrity.expected, 3);
        assert_eq!(s.integrity.recorded, 3);
    }

    #[test]
    fn a_missing_required_case_is_red() {
        let rows = complete_linux()
            .into_iter()
            .filter(|r| r.id != "CN-1")
            .collect();
        let s = build(rows, vec![], Some(0));
        assert_eq!(s.verdict, "RED");
        assert!(
            s.integrity
                .problems
                .iter()
                .any(|p| p.starts_with("CN-1: no row recorded")),
            "{:?}",
            s.integrity.problems
        );
    }

    #[test]
    fn a_nonempty_subset_of_passes_is_red() {
        let s = build(vec![row("PO-1", "policy", "PASS", "")], vec![], Some(0));
        assert_eq!(s.verdict, "RED");
        assert_eq!(s.counts.pass, 1);
    }

    #[test]
    fn a_duplicate_id_is_red() {
        let mut rows = complete_linux();
        rows.push(row("PO-1", "policy", "PASS", ""));
        let s = build(rows, vec![], Some(0));
        assert_eq!(s.verdict, "RED");
        assert!(
            s.integrity
                .problems
                .iter()
                .any(|p| p.contains("duplicate id"))
        );
    }

    #[test]
    fn a_row_for_an_unknown_case_is_red() {
        let mut rows = complete_linux();
        rows.push(row("PO-STALE", "policy", "PASS", ""));
        let s = build(rows, vec![], Some(0));
        assert_eq!(s.verdict, "RED");
        assert!(
            s.integrity
                .problems
                .iter()
                .any(|p| p.contains("not in the compiled suite"))
        );
    }

    #[test]
    fn an_unknown_result_is_red() {
        let mut rows = complete_linux();
        rows[0].result = "PASSED".into();
        let s = build(rows, vec![], Some(0));
        assert_eq!(s.verdict, "RED");
        assert!(
            s.integrity
                .problems
                .iter()
                .any(|p| p.contains("unknown result \"PASSED\""))
        );
    }

    #[test]
    fn a_malformed_row_file_is_red() {
        let s = build(
            complete_linux(),
            vec!["CN-1.jsonl: not a row".into()],
            Some(0),
        );
        assert_eq!(s.verdict, "RED");
        assert!(
            s.integrity
                .problems
                .iter()
                .any(|p| p.starts_with("malformed row"))
        );
    }

    #[test]
    fn a_skip_on_a_required_platform_is_red() {
        let mut rows = complete_linux();
        rows[1] = row(
            "CN-1",
            "containment",
            "SKIP",
            &format!("{SKIP_NOTE_PREFIX}linux"),
        );
        let s = build(rows, vec![], Some(0));
        assert_eq!(s.verdict, "RED");
        assert!(
            s.integrity
                .problems
                .iter()
                .any(|p| p.contains("required coverage not exercised"))
        );
    }

    #[test]
    fn a_skip_without_the_declared_note_is_red() {
        let mut rows = complete_linux();
        rows[2].note = "skipping: not today".into();
        let s = build(rows, vec![], Some(0));
        assert_eq!(s.verdict, "RED");
        assert!(
            s.integrity
                .problems
                .iter()
                .any(|p| p.contains("without the declared-inapplicable note"))
        );
    }

    #[test]
    fn a_pass_on_an_undeclared_platform_is_red() {
        let mut rows = complete_linux();
        rows[2] = row("CN-MAC", "containment", "PASS", "");
        let s = build(rows, vec![], Some(0));
        assert_eq!(s.verdict, "RED");
        assert!(
            s.integrity
                .problems
                .iter()
                .any(|p| p.contains("declared for [\"macos\"] only"))
        );
    }

    #[test]
    fn a_failing_cargo_run_with_all_passing_rows_is_red() {
        let s = build(complete_linux(), vec![], Some(101));
        assert_eq!(s.verdict, "RED");
        assert!(
            s.integrity
                .problems
                .iter()
                .any(|p| p.contains("cargo test exited 101 but no recorded row failed"))
        );
    }

    #[test]
    fn an_unreported_cargo_status_is_red() {
        let s = build(complete_linux(), vec![], None);
        assert_eq!(s.verdict, "RED");
        assert!(
            s.integrity
                .problems
                .iter()
                .any(|p| p.contains("exit status not reported"))
        );
    }

    #[test]
    fn a_fail_or_error_row_is_red() {
        for result in ["FAIL", "ERROR"] {
            let mut rows = complete_linux();
            rows[0].result = result.into();
            let s = build(rows, vec![], Some(101));
            assert_eq!(s.verdict, "RED", "{result}");
            assert!(
                s.integrity.problems.is_empty()
                    || s.integrity.problems == vec!["cargo test exited 101".to_string()]
            );
        }
    }

    #[test]
    fn all_skips_and_no_pass_is_red() {
        let s = Summary::build(
            "linux",
            "abc",
            Rows {
                rows: vec![row(
                    "CN-MAC",
                    "containment",
                    "SKIP",
                    &format!("{SKIP_NOTE_PREFIX}linux"),
                )],
                malformed: vec![],
            },
            &[SUITE[2]],
            Some(0),
        );
        assert_eq!(s.verdict, "RED");
        assert!(
            s.integrity
                .problems
                .iter()
                .any(|p| p.contains("no case passed"))
        );
    }

    #[test]
    fn a_wrong_category_is_red() {
        let mut rows = complete_linux();
        rows[1].category = "policy".into();
        let s = build(rows, vec![], Some(0));
        assert_eq!(s.verdict, "RED");
        assert!(
            s.integrity
                .problems
                .iter()
                .any(|p| p.contains("lives in \"containment\""))
        );
    }

    #[test]
    fn read_rows_reports_malformed_files_by_name() {
        let dir = tempfile::tempdir().unwrap();
        write_row(dir.path(), "PO-1", "policy", "d", "PASS", "");
        std::fs::write(dir.path().join("CN-1.jsonl"), "{not json\n").unwrap();
        std::fs::write(dir.path().join("CN-2.jsonl"), "").unwrap();
        std::fs::write(dir.path().join("CN-3.jsonl"), "{\"id\":\"CN-4\",\"category\":\"containment\",\"description\":\"d\",\"result\":\"PASS\",\"note\":\"\"}\n").unwrap();
        std::fs::write(dir.path().join("verdict.json"), "{}").unwrap();
        let found = read_rows(dir.path());
        assert_eq!(found.rows.len(), 1);
        assert_eq!(found.rows[0].id, "PO-1");
        assert_eq!(found.malformed.len(), 3, "{:?}", found.malformed);
        assert!(
            found
                .malformed
                .iter()
                .any(|m| m.starts_with("CN-1.jsonl: not a row"))
        );
        assert!(
            found
                .malformed
                .iter()
                .any(|m| m.starts_with("CN-2.jsonl: 0 rows"))
        );
        assert!(
            found
                .malformed
                .iter()
                .any(|m| m.contains("CN-3.jsonl: holds a row for id \"CN-4\""))
        );
    }

    #[test]
    fn the_compiled_manifest_names_every_case_file_once() {
        let mut ids: Vec<&str> = MANIFEST.iter().map(|c| c.id).collect();
        let n = ids.len();
        ids.sort();
        ids.dedup();
        assert_eq!(ids.len(), n, "duplicate ids in the manifest");
        assert!(n > 0);
        for spec in MANIFEST {
            assert_eq!(
                crate::category_for(spec.id),
                spec.category,
                "{}: id prefix and folder disagree",
                spec.id
            );
        }
    }

    // ── TEMPORARY QUARANTINE: the reducer side (test-integ/QUARANTINE.md) ─────────────────────
    // The quarantined cells are declared linux-only, like the real CN-W-05/CN-W-06.
    const QUARANTINE_SUITE: &[CaseSpec] = &[
        CaseSpec {
            id: "PO-1",
            category: "policy",
            platforms: &[],
        },
        CaseSpec {
            id: "CN-E-01",
            category: "containment",
            platforms: &[],
        },
        CaseSpec {
            id: "CN-W-05",
            category: "containment",
            platforms: &["linux"],
        },
        CaseSpec {
            id: "CN-W-06",
            category: "containment",
            platforms: &["linux"],
        },
    ];

    fn qnote(id: &str) -> String {
        crate::quarantine::note(crate::quarantine::lookup(id, "linux").expect("listed"))
    }

    /// A complete linux run with both quarantined cells recorded as authorized SKIPs.
    fn complete_linux_quarantined() -> Vec<Row> {
        vec![
            row("PO-1", "policy", "PASS", ""),
            row("CN-E-01", "containment", "PASS", ""),
            row("CN-W-05", "containment", "SKIP", &qnote("CN-W-05")),
            row("CN-W-06", "containment", "SKIP", &qnote("CN-W-06")),
        ]
    }

    fn build_on(platform: &str, rows: Vec<Row>, status: Option<i32>) -> Summary {
        Summary::build(
            platform,
            "abc",
            Rows {
                rows,
                malformed: vec![],
            },
            QUARANTINE_SUITE,
            status,
        )
    }

    #[test]
    fn the_authorized_linux_quarantine_is_the_reduced_green_gate_and_is_reported() {
        let s = build_on("linux", complete_linux_quarantined(), Some(0));
        assert_eq!(s.verdict, "GREEN", "{:?}", s.integrity.problems);
        assert_eq!(
            s.counts,
            Counts {
                total: 4,
                pass: 2,
                fail: 0,
                error: 0,
                skip: 2
            }
        );
        assert_eq!(
            s.coverage_gate,
            "reduced: 2 quarantined cell(s) on this platform"
        );
        let applied: Vec<(&str, bool)> = s.quarantine.iter().map(|q| (q.id, q.applied)).collect();
        assert_eq!(applied, vec![("CN-W-05", true), ("CN-W-06", true)]);
        assert!(s.quarantine.iter().all(|q| q.owner == "box-maintainers"
            && q.restore_when.contains("broad exec for a Linux tool leaf")));
        let json = serde_json::to_string(&s).unwrap();
        assert!(
            json.contains("\"coverage_gate\"")
                && json.contains("\"quarantine\"")
                && json.contains("TEMPORARY QUARANTINE"),
            "{json}"
        );
    }

    #[test]
    fn macos_has_no_quarantine_and_its_green_is_the_full_gate() {
        let rows = vec![
            row("PO-1", "policy", "PASS", ""),
            row("CN-E-01", "containment", "PASS", ""),
            row(
                "CN-W-05",
                "containment",
                "SKIP",
                &format!("{SKIP_NOTE_PREFIX}macos: declared for [linux]"),
            ),
            row(
                "CN-W-06",
                "containment",
                "SKIP",
                &format!("{SKIP_NOTE_PREFIX}macos: declared for [linux]"),
            ),
        ];
        let s = build_on("macos", rows, Some(0));
        assert_eq!(s.verdict, "GREEN", "{:?}", s.integrity.problems);
        assert_eq!(s.coverage_gate, "full");
        assert!(s.quarantine.is_empty());

        // A listed cell's linux note is NOT accepted on macos, where the case also applies.
        const EVERYWHERE: &[CaseSpec] = &[
            CaseSpec {
                id: "PO-1",
                category: "policy",
                platforms: &[],
            },
            CaseSpec {
                id: "CN-W-05",
                category: "containment",
                platforms: &[],
            },
        ];
        let s = Summary::build(
            "macos",
            "abc",
            Rows {
                rows: vec![
                    row("PO-1", "policy", "PASS", ""),
                    row("CN-W-05", "containment", "SKIP", &qnote("CN-W-05")),
                ],
                malformed: vec![],
            },
            EVERYWHERE,
            Some(0),
        );
        assert_eq!(s.verdict, "RED");
        assert!(
            s.integrity.problems.iter().any(|p| p
                .starts_with("CN-W-05: SKIP on macos, but the case is declared for this platform")),
            "{:?}",
            s.integrity.problems
        );
    }

    #[test]
    fn an_unlisted_case_skipping_is_red_even_with_a_quarantine_shaped_note() {
        let mut rows = complete_linux_quarantined();
        rows[1] = row(
            "CN-E-01",
            "containment",
            "SKIP",
            &qnote("CN-W-05").replace("CN-W-05", "CN-E-01"),
        );
        let s = build_on("linux", rows, Some(0));
        assert_eq!(s.verdict, "RED");
        assert!(
            s.integrity.problems.iter().any(|p| p
                .starts_with("CN-E-01: SKIP on linux, but the case is declared for this platform")),
            "{:?}",
            s.integrity.problems
        );
    }

    #[test]
    fn a_quarantined_cell_with_the_wrong_or_missing_reason_is_red() {
        for note in [
            "",
            "SKIP",
            "TEMPORARY QUARANTINE: CN-W-05 on linux: something else",
            &qnote("CN-W-05").replace("owner: box-maintainers", "owner: nobody"),
            &format!("{}{}", SKIP_NOTE_PREFIX, "linux: declared for [macos]"),
        ] {
            let mut rows = complete_linux_quarantined();
            rows[2] = row("CN-W-05", "containment", "SKIP", note);
            let s = build_on("linux", rows, Some(0));
            assert_eq!(s.verdict, "RED", "note {note:?} must not be accepted");
            assert!(s.integrity.problems.iter().any(|p| p.starts_with("CN-W-05: SKIP on linux with a note that is not the authorized TEMPORARY QUARANTINE note")), "{note:?}: {:?}", s.integrity.problems);
            assert!(
                !s.quarantine
                    .iter()
                    .find(|q| q.id == "CN-W-05")
                    .unwrap()
                    .applied,
                "not applied when the note is wrong"
            );
        }
    }

    #[test]
    fn a_quarantined_cell_that_ran_anyway_is_red_because_runner_and_reducer_disagree() {
        for result in ["PASS", "FAIL", "ERROR"] {
            let mut rows = complete_linux_quarantined();
            rows[2] = row("CN-W-05", "containment", result, "ran");
            let s = build_on("linux", rows, Some(0));
            assert_eq!(s.verdict, "RED", "{result}");
            assert!(
                s.integrity
                    .problems
                    .iter()
                    .any(|p| p.contains("TEMPORARY-QUARANTINED (runner and reducer disagree)")),
                "{result}: {:?}",
                s.integrity.problems
            );
        }
    }

    #[test]
    fn the_old_integrity_faults_still_defeat_a_quarantined_green() {
        // Missing row.
        let rows: Vec<Row> = complete_linux_quarantined()
            .into_iter()
            .filter(|r| r.id != "CN-E-01")
            .collect();
        let s = build_on("linux", rows, Some(0));
        assert_eq!(s.verdict, "RED");
        assert!(
            s.integrity
                .problems
                .iter()
                .any(|p| p.starts_with("CN-E-01: no row recorded"))
        );
        // Duplicate quarantined row.
        let mut rows = complete_linux_quarantined();
        rows.push(row("CN-W-05", "containment", "SKIP", &qnote("CN-W-05")));
        let s = build_on("linux", rows, Some(0));
        assert_eq!(s.verdict, "RED");
        assert!(
            s.integrity
                .problems
                .iter()
                .any(|p| p.contains("CN-W-05: 2 rows recorded (duplicate id)"))
        );
        // Cargo failure and unreported cargo status.
        assert_eq!(
            build_on("linux", complete_linux_quarantined(), Some(101)).verdict,
            "RED"
        );
        assert_eq!(
            build_on("linux", complete_linux_quarantined(), None).verdict,
            "RED"
        );
        // Another case failing stays RED.
        let mut rows = complete_linux_quarantined();
        rows[1] = row(
            "CN-E-01",
            "containment",
            "ERROR",
            "no shell:exec decision was journaled … 2411 Killed: 9 zsh",
        );
        let s = build_on("linux", rows, Some(101));
        assert_eq!(s.verdict, "RED");
        assert_eq!(s.counts.error, 1);
        // Malformed row alongside the quarantine.
        let s = Summary::build(
            "linux",
            "abc",
            Rows {
                rows: complete_linux_quarantined(),
                malformed: vec!["x.jsonl: not json".into()],
            },
            QUARANTINE_SUITE,
            Some(0),
        );
        assert_eq!(s.verdict, "RED");
        // Wrong platform/commit are the collector's checks and unchanged; the document still names them.
        assert_eq!(s.platform, "linux");
        assert_eq!(s.box_commit, "abc");
    }

    #[test]
    fn a_quarantined_cell_missing_its_row_is_still_a_missing_row() {
        let rows: Vec<Row> = complete_linux_quarantined()
            .into_iter()
            .filter(|r| r.id != "CN-W-05")
            .collect();
        let s = build_on("linux", rows, Some(0));
        assert_eq!(s.verdict, "RED");
        assert!(
            s.integrity
                .problems
                .iter()
                .any(|p| p.starts_with("CN-W-05: no row recorded")),
            "{:?}",
            s.integrity.problems
        );
        assert!(
            !s.quarantine
                .iter()
                .find(|q| q.id == "CN-W-05")
                .unwrap()
                .applied
        );
    }
}
