//! Containment suite — one test binary aggregating every case in
//! tests/containment/. The module list is generated by build.rs; add a case by
//! dropping a file in tests/containment/ (no edit here needed).
#[path = "phase3/mod.rs"]
mod phase3;
include!(concat!(env!("OUT_DIR"), "/containment_mods.rs"));
