//! Monty suite — one test binary aggregating every case in tests/monty/.
//! The module list is generated by build.rs; add a case by dropping a file in
//! tests/monty/ (no edit here needed). These drive the box's Python interpreter
//! (Monty) via the `python3` alias (`MO-*` ids) and assert its policy-judged
//! effects and sandbox.
include!(concat!(env!("OUT_DIR"), "/monty_mods.rs"));
