//! Policy suite — one test binary aggregating every case in tests/policy/.
//! The module list is generated by build.rs; add a case by dropping a file in
//! tests/policy/ (no edit here needed).
include!(concat!(env!("OUT_DIR"), "/policy_mods.rs"));
