//! Shell suite — one test binary aggregating every case in tests/shell/.
//! The module list is generated by build.rs; add a case by dropping a file in
//! tests/shell/ (no edit here needed). These drive the hosted Strands Shell
//! (`SH-*` ids) through the mediated route and assert built-in behaviour.
include!(concat!(env!("OUT_DIR"), "/shell_mods.rs"));
