//! Telemetry suite — one test binary aggregating every case in tests/telemetry/.
//! The module list is generated by build.rs; add a case by dropping a file in
//! tests/telemetry/ (no edit here needed).
include!(concat!(env!("OUT_DIR"), "/telemetry_mods.rs"));
